name: vannygee
favicon: null
layout_spectrum: 0.6117132492363453
typography_spectrum: 0.7934135955292732
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.1744087866973132
  lightness: 0.17786361323669553
  saturation: 0.01946228160522878
  rhythmicContrast: 0.5500123847741634
purpose: []
