name: vannygee
favicon: null
layout_spectrum: 0.62031
typography_spectrum: 0.26836
title: vannygee
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-73577113-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#100b0f'
    - '#c496d6'
    - '#7475f5'
    - '#51484d'
    - '#ffeabe'
  brandStrength: 0.6875
  lightness: 0
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
